server.port: 8081 # Порт, на котором будет работать сервер
spring:
  application.name: product-selector-backend # Имя приложения
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres # URL для подключения к базе данных PostgresSQL
    username: postgres # Имя пользователя для подключения к базе данных
    password: 123 # Пароль для подключения к базе данных
    driver-class-name: org.postgresql.Driver # Класс драйвера для PostgresSQL
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect # Платформа базы данных для JPA (Hibernate)
    hibernate.ddl-auto: update # update: обновляет схему без удаления данных
    show-sql: true # Включает логирование SQL-запросов в консоль
    properties.hibernate.format_sql: true # Форматирует SQL-запросы в логах для лучшей читаемости
token:
  signing:
    key: 53A73E5F1C4E0A2D3B5F2D784E6A1B423D6F247D1F6E5C3A596D635A75327855