PUT http://localhost:8081/user
Content-Type: application/json

{
  "id": 1,
  "name": "John",
  "surname": "Doe",
  "email": "john.doe.updated@example.com",
  "password": "newpassword123",
  "birthDate": "1990-01-01",
  "registrationDate": "2023-08-17",
  "accessLevel": "ADMIN"
}

