POST http://localhost:8081/recipe
Content-Type: application/json

{
  "name": "Vegetarian Pasta",
  "description": "A healthy and delicious pasta dish.",
  "vegan": true,
  "difficultyLevel": "EASY",
  "rating": 4,
  "image": "http://example.com/vegetarian-pasta.png",
  "productIds": [1, 2, 3]
}

